source 'https://rubygems.org'
ruby '3.4.1'

gem 'middleman', '~> 4.6'
gem 'middleman-autoprefixer', '~> 3.0'
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]
gem 'wdm', '~> 0.1', platforms: [:mswin, :mingw]

gem 'middleman-dotenv'
gem 'middleman-minify-html'
gem 'dotenv'
gem 'rake'
gem 'graphql-client'
gem 'nokogiri'
gem 'redcarpet'
gem 'activesupport'
gem 'sanitize'
gem 'public_suffix'
gem 'httparty'
gem 'jwt'
gem 'redis'
gem 'icalendar'
gem 'blurhash', git: 'https://github.com/gesteves/blurhash', branch: 'master'
gem 'mini_magick'
gem 'rspec'
gem 'htmlentities'
gem 'text'
gem 'humanize'
gem 'benchmark'
gem 'rdoc'
