
[functions]
  node_bundler = "esbuild"

[functions.og]
  included_files = [
    "build/og/data.json",
    "source/fonts/IBMPlexSansCondensed-Bold.ttf"
  ]
  external_node_modules = ["@vercel/og"]

[images]
  remote_images = [".*\\.ctfassets\\.net/.*", ".*\\.cloudfront\\.net/.*"]

[build]
  base = "web"
  command = "bundle exec rake build"
  publish = "build/"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "no-referrer-when-downgrade"

[[headers]]
  for = "/.well-known/site.standard.publication"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"

[[redirects]]
  from = "/.well-known/host-meta*"
  to = "https://fed.brid.gy/.well-known/host-meta:splat"
  status = 302
[[redirects]]
  from = "/.well-known/webfinger*"
  to = "https://fed.brid.gy/.well-known/webfinger"
  status = 302
