// On-demand loader for Pagefind's Component UI.
//
// Both files used to sit in the <head> on every page (partials/_head.html.erb): the
// stylesheet was render-blocking and the module competed for bandwidth during first
// paint, for a UI that doesn't exist until someone opens search. Nothing auto-opens
// the modal, so neither is needed before the page renders.
//
// Loading happens in three layers, so in practice nobody ever waits:
//   1. an idle preload once the page has finished loading (the one that does the work —
//      off the critical path, but resident long before any realistic click);
//   2. an intent prefetch on hover/focus of a Search trigger;
//   3. an awaited call in `search#open`, guaranteeing correctness for a click that beats
//      both of the above.
//
// Everything routes through the one memoized `loadPagefind()`, so the layers can't
// double-inject.

const CSS_HREF = '/pagefind/pagefind-component-ui.css';
const JS_SRC = '/pagefind/pagefind-component-ui.js';

// Module scope, so it survives Turbo navigations along with the injected elements.
let loading;
let idleScheduled = false;

/**
 * Resolves once an element has finished loading, or failed to. Failure is not
 * exceptional here: in development `/pagefind/` doesn't exist (the index is generated by
 * `npm run pagefind` against `build/`), and search is a no-op there by design.
 * @param {HTMLElement} element - The element to watch.
 * @returns {Promise<boolean>} Whether the element loaded successfully.
 */
function settleOnLoad(element) {
  return new Promise((resolve) => {
    element.addEventListener('load', () => resolve(true), { once: true });
    element.addEventListener('error', () => resolve(false), { once: true });
  });
}

/**
 * Injects Pagefind's stylesheet and component module, once per page lifetime.
 * @returns {Promise<boolean>} Resolves true once `<pagefind-modal>` is defined, or false
 *   if either asset failed to load (development, or a bad deploy).
 */
export function loadPagefind() {
  if (loading) return loading;

  const css = document.createElement('link');
  css.rel = 'stylesheet';
  css.href = CSS_HREF;
  const cssSettled = settleOnLoad(css);

  // ⚠️ Insert BEFORE the first existing stylesheet rather than appending. The dark-mode
  // `--pf-*` remap in stylesheets/components/_pagefind.scss is an unlayered `:root` block
  // that beats Pagefind's own unlayered `:root` defaults only by sitting later in SOURCE
  // order — see that partial's header for why it can't be layered instead. The cascade
  // follows document order, not load order, so inserting here reproduces the old <head>
  // ordering exactly. Append it and the modal renders permanently light in dark mode.
  document.head.insertBefore(
    css,
    document.head.querySelector('link[rel="stylesheet"]')
  );

  const js = document.createElement('script');
  js.type = 'module';
  js.src = JS_SRC;
  const jsSettled = settleOnLoad(js);
  // No `data-turbo-track` on either element on purpose: Turbo removes stylesheets from the
  // old <head> only when they're marked `data-turbo-track="dynamic"` and missing from the
  // incoming one. Unmarked, these survive navigation — which is what we want, since no
  // rendered page will ever contain them.
  document.head.appendChild(js);

  loading = Promise.all([cssSettled, jsSettled]).then(([cssOk, jsOk]) => {
    // Only wait on the custom element if the module actually loaded — `whenDefined` for a
    // script that 404'd never settles, which would hang `search#open` forever in dev.
    if (!jsOk) return false;
    return customElements
      .whenDefined('pagefind-modal')
      .then(() => cssOk && jsOk);
  });

  return loading;
}

/**
 * Schedules the load for the first idle moment after the page has finished loading, so it
 * never competes with the critical path. Idempotent; safe to call on every `turbo:load`.
 */
export function preloadPagefindWhenIdle() {
  if (idleScheduled) return;
  idleScheduled = true;

  const schedule = () => {
    // Safari only gained requestIdleCallback in 17; fall back to a plain timeout.
    if (typeof window.requestIdleCallback === 'function') {
      window.requestIdleCallback(() => loadPagefind(), { timeout: 3000 });
    } else {
      setTimeout(() => loadPagefind(), 1000);
    }
  };

  if (document.readyState === 'complete') {
    schedule();
  } else {
    window.addEventListener('load', schedule, { once: true });
  }
}
