import * as Turbo from '@hotwired/turbo';
import { Application } from '@hotwired/stimulus';
import '@web.awesome.me/webawesome-pro/dist/styles/themes/default.css';
import '@web.awesome.me/webawesome-pro/dist/components/skeleton/skeleton.js';
import '@web.awesome.me/webawesome-pro/dist/components/relative-time/relative-time.js';
import '@web.awesome.me/webawesome-pro/dist/components/toast/toast.js';
import '@web.awesome.me/webawesome-pro/dist/components/input/input.js';
import '@web.awesome.me/webawesome-pro/dist/components/textarea/textarea.js';
import '@web.awesome.me/webawesome-pro/dist/components/button/button.js';
import '@web.awesome.me/webawesome-pro/dist/components/scroller/scroller.js';
import './lib/patch_scroller_aria';

import BackToTopController from './controllers/back_to_top_controller';
import ClipboardController from './controllers/clipboard_controller';
import CurrentYearController from './controllers/current_year_controller';
import ImagePlaceholderController from './controllers/image_placeholder_controller';
import LiveUpdateController from './controllers/live_update_controller';
import NavController from './controllers/nav_controller';
import OauthCallbackController from './controllers/oauth_callback_controller';
import PageController from './controllers/page_controller';
import PublishDateController from './controllers/publish_date_controller';
import ShareController from './controllers/share_controller';
import UnitsController from './controllers/units_controller';

window.Stimulus = Application.start();
Stimulus.register('back-to-top', BackToTopController);
Stimulus.register('clipboard', ClipboardController);
Stimulus.register('current-year', CurrentYearController);
Stimulus.register('image-placeholder', ImagePlaceholderController);
Stimulus.register('live-update', LiveUpdateController);
Stimulus.register('nav', NavController);
Stimulus.register('oauth-callback', OauthCallbackController);
Stimulus.register('page', PageController);
Stimulus.register('publish-date', PublishDateController);
Stimulus.register('share', ShareController);
Stimulus.register('units', UnitsController);
