Blizzard:
  adverse_weather: true
  precipitation: snow
  phrases:
    currently: there's a blizzard
    forecast: calls for blizzard conditions
    simplified: Blizzard
  icon: snow-blowing
  emoji: "❄️"

BlowingDust:
  adverse_weather: true
  phrases:
    currently: there's blowing dust
    forecast: calls for blowing dust
    simplified: Blowing dust
  icon: sun-dust
  emoji: "💨"

BlowingSnow:
  adverse_weather: true
  precipitation: snow
  phrases:
    currently: there's blowing snow
    forecast: calls for blowing snow
    simplified: Blowing snow
  icon: snow-blowing
  emoji: "🌨️"

Breezy:
  adverse_weather: false
  phrases:
    currently: it's breezy
    forecast: is breezy
    simplified: Breezy
  icon: wind
  emoji: "🍃"

Clear:
  adverse_weather: false
  phrases:
    currently: it's clear
    forecast: is clear
    simplified: Clear
  icon:
    day: sun
    night: moon-stars
  emoji:
    day: "☀️"
    night: "🌙"

Cloudy:
  adverse_weather: false
  phrases:
    currently: it's cloudy
    forecast: is cloudy
    simplified: Cloudy
  icon: clouds
  emoji: "☁️"

Drizzle:
  adverse_weather: true
  precipitation: rain
  phrases:
    currently: it's raining lightly
    forecast: calls for light rain
    simplified: Drizzle
  icon: cloud-drizzle
  emoji: "🌧️"

Dust:
  adverse_weather: true
  phrases:
    currently: it's dusty
    forecast: calls for dusty conditions
    simplified: Dust
  icon: sun-dust
  emoji: "🌫️"

Flurries:
  adverse_weather: true
  precipitation: snow
  phrases:
    currently: there are flurries
    forecast: calls for flurries
    simplified: Flurries
  icon: cloud-snow
  emoji: "🌨️"

Fog:
  adverse_weather: true
  phrases:
    currently: it's foggy
    forecast: is foggy
    simplified: Fog
  icon: cloud-fog
  emoji: "🌫️"

FreezingDrizzle:
  adverse_weather: true
  precipitation: ice
  phrases:
    currently: there's a freezing drizzle
    forecast: calls for freezing drizzle
    simplified: Freezing drizzle
  icon: cloud-hail-mixed
  emoji: "🌧️"

FreezingRain:
  adverse_weather: true
  precipitation: ice
  phrases:
    currently: there's freezing rain
    forecast: calls for freezing rain
    simplified: Freezing rain
  icon: cloud-sleet
  emoji: "🌧️"

Frigid:
  adverse_weather: true
  phrases:
    currently: it's frigid outside
    forecast: is extremely cold
    simplified: Frigid
  icon: temperature-snow
  emoji: "🥶"

Hail:
  adverse_weather: true
  precipitation: ice
  phrases:
    currently: it's hailing
    forecast: calls for hail
    simplified: Hail
  icon: cloud-hail
  emoji: "🧊"

Haze:
  adverse_weather: true
  phrases:
    currently: it's hazy
    forecast: is hazy
    simplified: Haze
  icon: cloud-fog
  emoji: "🌫️"

HeavyRain:
  adverse_weather: true
  precipitation: rain
  phrases:
    currently: it's raining heavily
    forecast: calls for heavy rain
    simplified: Heavy rain
  icon: cloud-showers-heavy
  emoji: "🌧️"

HeavySnow:
  adverse_weather: true
  precipitation: snow
  phrases:
    currently: it's snowing heavily
    forecast: calls for heavy snow
    simplified: Heavy snow
  icon: snowflakes
  emoji: "❄️"

Hot:
  adverse_weather: true
  phrases:
    currently: it's hot outside
    forecast: is extremely hot
    simplified: Hot
  icon: temperature-high
  emoji: "🥵"

Hurricane:
  adverse_weather: true
  precipitation: rain
  phrases:
    currently: there's a hurricane
    forecast: calls for hurricane conditions
    simplified: Hurricane
  icon: hurricane
  emoji: "🌀"

IsolatedThunderstorms:
  adverse_weather: true
  precipitation: rain
  phrases:
    currently: there are isolated thunderstorms
    forecast: calls for isolated thunderstorms
    simplified: Isolated thunderstorms
  icon: cloud-bolt
  emoji: "⛈️"

MixedRainAndSleet:
  adverse_weather: true
  precipitation: mixed
  phrases:
    currently: there's a mix of rain and sleet
    forecast: calls for mixed rain and sleet
    simplified: Mixed rain & sleet
  icon: cloud-sleet
  emoji: "🌨️"

MixedRainAndSnow:
  adverse_weather: true
  precipitation: mixed
  phrases:
    currently: there's a mix of rain and snow
    forecast: calls for mixed rain and snow
    simplified: Mixed rain & snow
  icon: cloud-sleet
  emoji: "🌨️"

MixedRainfall:
  adverse_weather: true
  precipitation: mixed
  phrases:
    currently: there's mixed rainfall
    forecast: calls for mixed rainfall
    simplified: Mixed rainfall
  icon: cloud-sleet
  emoji: "🌧️"

MixedSnowAndSleet:
  adverse_weather: true
  precipitation: mixed
  phrases:
    currently: there's a mix of snow and sleet
    forecast: calls for mixed snow and sleet
    simplified: Mixed snow & sleet
  icon: cloud-hail-mixed
  emoji: "🌨️"

MostlyClear:
  adverse_weather: false
  phrases:
    currently: it's mostly clear
    forecast: is mostly clear
    simplified: Mostly clear
  icon:
    day: sun-cloud
    night: moon-cloud
  emoji:
    day: "🌤️"
    night: "🌙"

MostlyCloudy:
  adverse_weather: false
  phrases:
    currently: it's mostly cloudy
    forecast: is mostly cloudy
    simplified: Mostly cloudy
  icon:
    day: clouds-sun
    night: clouds-moon
  emoji:
    day: "🌥️"
    night: "☁️"

PartlyCloudy:
  adverse_weather: false
  phrases:
    currently: it's partly cloudy
    forecast: is partly cloudy
    simplified: Partly cloudy
  icon:
    day: clouds-sun
    night: clouds-moon
  emoji:
    day: "⛅"
    night: "☁️"

Rain:
  adverse_weather: true
  precipitation: rain
  phrases:
    currently: it's raining
    forecast: calls for rain
    simplified: Rain
  icon: cloud-rain
  emoji: "🌧️"

ScatteredShowers:
  adverse_weather: true
  precipitation: rain
  phrases:
    currently: there are scattered showers
    forecast: calls for scattered showers
    simplified: Scattered showers
  icon: cloud-showers
  emoji:
    day: "🌦️"
    night: "🌧️"

ScatteredSnowShowers:
  adverse_weather: true
  precipitation: snow
  phrases:
    currently: there are scattered snow showers
    forecast: calls for scattered snow showers
    simplified: Scattered snow showers
  icon: cloud-snow
  emoji: "🌨️"

ScatteredThunderstorms:
  adverse_weather: true
  precipitation: rain
  phrases:
    currently: there are scattered thunderstorms
    forecast: calls for scattered thunderstorms
    simplified: Scattered thunderstorms
  icon: cloud-bolt
  emoji: "⛈️"

SevereThunderstorm:
  adverse_weather: true
  precipitation: rain
  phrases:
    currently: there's a severe thunderstorm
    forecast: calls for severe thunderstorms
    simplified: Severe thunderstorm
  icon: bolt-lightning
  emoji: "⛈️"

Sleet:
  adverse_weather: true
  precipitation: ice
  phrases:
    currently: it's sleeting
    forecast: calls for sleet
    simplified: Sleet
  icon: cloud-snow
  emoji: "🌨️"

Smoke:
  adverse_weather: true
  phrases:
    currently: it's smoky
    forecast: calls for smoky conditions
    simplified: Smoke
  icon: fire-smoke
  emoji: "🌫️"

Snow:
  adverse_weather: true
  precipitation: snow
  phrases:
    currently: it's snowing
    forecast: calls for snow
    simplified: Snow
  icon: snowflake
  emoji: "🌨️"

SnowShowers:
  adverse_weather: true
  precipitation: snow
  phrases:
    currently: there are snow showers
    forecast: calls for snow showers
    simplified: Snow showers
  icon: cloud-hail-mixed
  emoji: "🌨️"

StrongStorms:
  adverse_weather: true
  precipitation: rain
  phrases:
    currently: there are strong storms
    forecast: calls for strong storms
    simplified: Strong storms
  icon: bolt-lightning
  emoji: "⛈️"

SunFlurries:
  adverse_weather: true
  precipitation: snow
  phrases:
    currently: it's sunny with snow flurries
    forecast: calls for sun and snow flurries
    simplified: Sun flurries
  icon: cloud-snow
  emoji: "🌨️"

SunShowers:
  adverse_weather: true
  precipitation: rain
  phrases:
    currently: it's sunny and raining
    forecast: calls for sun and rain
    simplified: Sun showers
  icon: cloud-sun-rain
  emoji:
    day: "🌦️"
    night: "🌧️"

Thunderstorms:
  adverse_weather: true
  precipitation: rain
  phrases:
    currently: there are thunderstorms
    forecast: calls for thunderstorms
    simplified: Thunderstorms
  icon: cloud-bolt
  emoji: "⛈️"

Tornado:
  adverse_weather: true
  phrases:
    currently: there's a tornado
    forecast: calls for tornado conditions
    simplified: Tornado
  icon: tornado
  emoji: "🌪️"

TropicalStorm:
  adverse_weather: true
  precipitation: rain
  phrases:
    currently: there's a tropical storm
    forecast: calls for a tropical storm
    simplified: Tropical storm
  icon: hurricane
  emoji: "🌀"

Windy:
  adverse_weather: true
  phrases:
    currently: it's windy
    forecast: calls for windy conditions
    simplified: Windy
  icon: wind
  emoji: "🌬️"

WintryMix:
  adverse_weather: true
  precipitation: mixed
  phrases:
    currently: there's a wintry mix
    forecast: calls for a wintry mix
    simplified: Wintry mix
  icon: cloud-sleet
  emoji: "🌨️"
