source 'https://rubygems.org'
ruby '4.0.6'

gem 'middleman', '~> 4.6'
gem 'middleman-autoprefixer', '~> 3.0'
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]
gem 'wdm', '~> 0.1', platforms: [:mswin, :mingw]

gem 'middleman-dotenv'
gem 'middleman-minify-html'
gem 'dotenv'
gem 'rake'
gem 'graphql-client'
gem 'nokogiri'
gem 'redcarpet'
gem 'activesupport'
gem 'sanitize'
gem 'public_suffix'
gem 'httparty'
gem 'redis'
gem 'blurhash', git: 'https://github.com/gesteves/blurhash', branch: 'master'
gem 'ruby-vips'
gem 'ostruct'
gem 'rspec'
gem 'htmlentities'
gem 'humanize'
# Scans the bundle for gems with known CVEs; run by the security job in web.yml. This app's
# build-time dependencies parse untrusted content (nokogiri, redcarpet, sanitize), so it wants
# the same CVE gate the api has had.
gem 'bundler-audit', require: false
