require 'dotenv/tasks'
require 'rake/clean'
require_relative 'lib/utils/redis_connection'

# Require all Ruby files in the lib/data and lib/utils directories
Dir["lib/data/*.rb"].each { |file| require_relative file }
Dir["lib/utils/*.rb"].each { |file| require_relative file }

# Import tasks from lib/tasks
Dir.glob('lib/tasks/**/*.rake').each { |r| import r }

def initialize_redis
  RedisConnection.connection
end
